import type { CategorySettings } from "../../../src/settings";

export const Selectors: Record<keyof CategorySettings, string[]> = {
  image: ["img", "svg", "[role~='img']"] as const,
  formControl: [
    "input:not([type='hidden']):not([type='button']):not([type='submit']):not([type='reset']):not([type='image'])",
    "textarea",
    "select",
    '[role~="checkbox"]',
    '[role~="combobox"]',
    '[role~="radio"]',
    '[role~="searchbox"]',
    '[role~="slider"]',
    '[role~="spinbutton"]',
    '[role~="switch"]',
    '[role~="textbox"]',
    '[role~="menuitemcheckbox"]',
    '[role~="menuitemradio"]',
    "label",
    "fieldset",
    "form",
  ] as const,
  link: ["a", "area", '[role~="link"]'] as const,
  button: [
    "button",
    "details > summary:first-child",
    '[role~="button"]',
    '[role~="menuitem"]',
    'input[type="button"]',
    'input[type="submit"]',
    'input[type="reset"]',
    'input[type="image"]',
  ] as const,
  heading: [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    '[role~="heading"]',
    "hgroup",
  ] as const,
  section: [
    "article",
    "section",
    "nav",
    "aside",
    "footer",
    "header",
    "main",
    "form",
    "search",
    "dialog",
    "iframe",
    '[role~="article"]',
    '[role~="banner"]',
    '[role~="complementary"]',
    '[role~="contentinfo"]',
    '[role~="main"]',
    '[role~="form"]',
    '[role~="navigation"]',
    '[role~="region"]',
    '[role~="search"]',
    '[role~="application"]',
    '[role~="dialog"]',
    '[role~="alertdialog"]',
  ] as const,
  lang: ["[lang]", "[xml\\:lang]"] as const,
  page: [],
  table: [
    "table",
    "th",
    "td",
    '[role~="table"]',
    '[role~="grid"]',
    '[role~="columnheader"]',
    '[role~="rowheader"]',
    '[role~="gridcell"]',
    '[role~="cell"]',
  ] as const,
  list: [
    "ul",
    "ol",
    "menu",
    "li",
    "dl",
    "dt",
    "dd",
    '[role~="list"]',
    '[role~="listitem"]',
    '[role~="directory"]',
    '[role~="menu"]',
    '[role~="menubar"]',
    '[role~="menuitem"]',
    '[role~="menuitemcheckbox"]',
    '[role~="menuitemradio"]',
  ] as const,
  waiAria: [
    "[role]",
    // WAI-ARIA 1.2 Complete Attribute List
    "[aria-activedescendant]",
    "[aria-atomic]",
    "[aria-autocomplete]",
    "[aria-braillelabel]",
    "[aria-brailleroledescription]",
    "[aria-busy]",
    "[aria-checked]",
    "[aria-colcount]",
    "[aria-colindex]",
    "[aria-colindextext]",
    "[aria-colspan]",
    "[aria-controls]",
    "[aria-current]",
    "[aria-describedby]",
    "[aria-description]",
    "[aria-details]",
    "[aria-disabled]",
    "[aria-dropeffect]",
    "[aria-errormessage]",
    "[aria-expanded]",
    "[aria-flowto]",
    "[aria-grabbed]",
    "[aria-haspopup]",
    "[aria-hidden]",
    "[aria-invalid]",
    "[aria-keyshortcuts]",
    "[aria-label]",
    "[aria-labelledby]",
    "[aria-level]",
    "[aria-live]",
    "[aria-modal]",
    "[aria-multiline]",
    "[aria-multiselectable]",
    "[aria-orientation]",
    "[aria-owns]",
    "[aria-placeholder]",
    "[aria-posinset]",
    "[aria-pressed]",
    "[aria-readonly]",
    "[aria-relevant]",
    "[aria-required]",
    "[aria-roledescription]",
    "[aria-rowcount]",
    "[aria-rowindex]",
    "[aria-rowindextext]",
    "[aria-rowspan]",
    "[aria-selected]",
    "[aria-setsize]",
    "[aria-sort]",
    "[aria-valuemax]",
    "[aria-valuemin]",
    "[aria-valuenow]",
    "[aria-valuetext]",
  ] as const,
  tabIndex: ["[tabindex]"] as const,
};
