import { CategorySettings } from "../../settings";

export const Selectors: Record<keyof CategorySettings, string[]> = {
  image: ["img", "[role~='img']"] as const,
  formControl: [
    "input:not([type='hidden']):not([type='button']):not([type='submit']):not([type='reset']):not([type='image'])",
    "textarea",
    "select",
    '[role~="checkbox"]',
    '[role~="combobox"]',
    '[role~="radio"]',
    '[role~="searchbox"]',
    '[role~="slider"]',
    '[role~="spinbutton"]',
    '[role~="switch"]',
    '[role~="textbox"]',
    '[role~="menuitemcheckbox"]',
    '[role~="menuitemradio"]',
    "label",
    "fieldset",
    "form",
  ] as const,
  link: ["a", "area", '[role~="link"]'] as const,
  button: [
    "button",
    "details > summary:first-child",
    '[role~="button"]',
    '[role~="menuitem"]',
    'input[type="button"]',
    'input[type="submit"]',
    'input[type="reset"]',
    'input[type="image"]',
  ] as const,
  heading: [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    '[role~="heading"]',
    "hgroup",
  ] as const,
  ariaHidden: ["[aria-hidden~='true']"] as const,
  section: [
    "article",
    "section",
    "nav",
    "aside",
    "footer",
    "header",
    "main",
    "form",
    "search",
    "dialog",
    '[role~="article"]',
    '[role~="banner"]',
    '[role~="complementary"]',
    '[role~="contentinfo"]',
    '[role~="main"]',
    '[role~="form"]',
    '[role~="navigation"]',
    '[role~="region"]',
    '[role~="search"]',
    '[role~="application"]',
    '[role~="dialog"]',
    '[role~="alertdialog"]',
  ] as const,
  lang: ["[lang]", "[xml\\:lang]"] as const,
  page: [],
  table: [
    "table",
    "th",
    "td",
    '[role~="table"]',
    '[role~="grid"]',
    '[role~="columnheader"]',
    '[role~="rowheader"]',
    '[role~="gridcell"]',
    '[role~="cell"]',
  ] as const,
};
